---
- hosts: all
  remote_user: pi
  sudo: yes

  tasks:
    - name: Shutdown the webapp
      service: name=webapp state=stopped pattern="webapp.d"
      ignore_errors: yes

    - name: Remove the current deployed webapp
      file: path=/home/pi/webapp/app state=absent

    - name: Remove the temp directory
      file: path=/home/pi/tmp state=absent

    - name: Create the empty webapp directory
      file: path=/home/pi/webapp/app state=directory owner=pi group=pi

    - name: Get github repo
      git: repo=https://github.com/graeme-lockley/charcuterie-controller.git dest=/home/pi/tmp version=HEAD

    - name: Copy the webapp into its target location
      raw: cp -R /home/pi/tmp/src/webapp/* /home/pi/webapp/app

    - name: Set execute privilages on the webapp bin contents
      raw: chmod 755 /home/pi/webapp/app/bin/*

    - name: Copy the webapp service into its target location
      raw: cp /home/pi/webapp/app/bin/webapp /etc/init.d

    - name: Change the owner of the webapp service to root
      raw: chown root /etc/init.d/webapp

    - name: Change the group of the webapp service to root
      raw: chgrp root /etc/init.d/webapp

    - name: Change the webapp directory owner
      shell: chdir=/home/pi/webapp sudo chown -R pi . *

    - name: Change the webapp directory group
      shell: chdir=/home/pi/webapp sudo chgrp -R pi . *

    - name: Install all of the required webapp gems
      sudo: no
      shell: chdir=/home/pi/webapp/app bundle install

    - name: Remove tmp directory
      file: path=/home/pi/tmp state=absent

    - name: Start the webapp
      service: name=webapp state=started enabled=yes pattern="webapp.d"

    - name: Ensure that the webapp is automatically started when booting the pi
      service: name=webapp enabled=yes
